#include <com/sun/star/uno/XInterface.idl>

module stormray {

    interface XElmoFire : com::sun::star::uno::XInterface
        {
            string ElmoStr([in] sequence<any> args);
            string ElmoVal([in] sequence<any> args);
        };

};
