#include <com/sun/star/uno/XInterface.idl>

module addins {

    interface XStElmoFire : com::sun::star::uno::XInterface
        {
            string elmostr([in] sequence<any> args);
            any elmoval([in] sequence<any> args);
        };

};
